name: macos

on:
  push:
    branches: [ "develop", "release/*" ]
  pull_request:
    branches: [ "develop", "release/*" ]

env:
  BUILD_TYPE: Release

jobs:        
  build-mac-intel:
    runs-on: macos-12
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
          brew install gperf dos2unix bison flex ninja perl
          echo 'export PATH="$(brew --prefix bison)/bin:$PATH"' >> /Users/runner/.bashrc
          export LDFLAGS="-L$(brew --prefix bison)/lib"
          source ~/.bashrc
          brew link bison --force

          
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build  -G 'Ninja' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --parallel --config ${{env.BUILD_TYPE}}

  build-mac-arm:
    runs-on: macos-latest
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
          brew install gperf dos2unix bison flex ninja perl
          echo 'export PATH="$(brew --prefix bison)/bin:$PATH"' >> /Users/runner/.bashrc
          export LDFLAGS="-L$(brew --prefix bison)/lib"
          source ~/.bashrc
          brew link bison --force

          
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build  -G 'Ninja' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --parallel --config ${{env.BUILD_TYPE}}
