name: windows

on:
  push:
    branches: [ "develop", "release/*" ]
  pull_request:
    branches: [ "develop", "release/*" ]

env:
  BUILD_TYPE: Release
  
jobs:

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - name: Disable autocrlf
      shell: pwsh
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install gperf using Chocolatey
      shell: pwsh
      run: |
        choco install gperf winflexbison3 -y
        
    - name: '⚙️ Install CMake'
      uses: lukka/get-cmake@latest
    
    - name: Build with cmake
      shell: pwsh
      run: |
        cmake.exe -B build/ -G "Ninja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake.exe --build build/ --parallel --config ${{env.BUILD_TYPE}}
        
  build-windows-msys2:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys:
          - mingw64
          - clang64
          - ucrt64
    defaults:
      run:
         shell: msys2 {0}
    steps:
    - name: Disable autocrlf
      shell: pwsh
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        cache: true
        update: true
        install: >-
          bison 
          flex
          dos2unix 
        pacboy: >-
          cmake:p 
          gcc:p 
          make:p 
          gperf:p
          
    - name: Build with cmake
      run: |
        cmake.exe -B build/ -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake.exe --build build/ -j`nproc` --config ${{env.BUILD_TYPE}}
    
